config:
  node_agent: 'docker_compose'
  deploy_template: '.sqa/docker-compose_custom.yml'
#  project_repos:
#    eosc-perf:
#      repo: 'https://github.com/EOSC-synergy/eosc-perf.git'
#      branch: 'backend'

environment:
  JPL_DOCKERFORCEBUILD: 'true'
  LANG: C.UTF-8

sqa_criteria:
  qc_doc:
    repos:
      eosc-perf:
        container: perf-testing
        commands: 
        - bash -c "pip3 install -r ./requirements-docs.txt && cd docs/ && make html"

timeout: 900
